### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by Fire-Liu001** [Harryqu123/LMC#1]
I have two problems when running the code, could you please answer them for me?
1.Key xxx is not found in dictionary....
2.ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
Thank you very much！

**Comment by Harryqu123** [comment]
Hi there,
Thanks for your interest in our work.
After receiving your query, we have just rechecked our uploaded code. Specifically, while we fail to reproduce the bug you screenshotted, we find that we do miss uploading the tinyimagenet.sh which can facilitate the downloading process of the tinyimagenet dataset.
We just uploaded this file and found that, with tinyimagenet dataset downloaded through this sh file, everything seems to be fine on our side. Thus, could we politely suggest you use the newly uploaded sh file and re-run our code?
Do tell me if you still face error so that I can help you further.
Sorry for any inconvenience caused and happy new year.
